export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Bosnia",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mexico",
  "Moldova",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const LANGUAGES = ["English"];

export const INDUSTRIES = [
  "Accounting & Finance",
  "Advertising & Marketing",
  "Aerospace & Defense",
  "Agriculture & Farming",
  "Architecture & Design",
  "Artificial Intelligence & ML",
  "Automotive",
  "Aviation",
  "Banking & Financial Services",
  "Biotechnology",
  "Broadcasting & Media",
  "Chemical",
  "Civil Engineering",
  "Cloud Computing",
  "Construction",
  "Consulting",
  "Consumer Electronics",
  "Content Creation",
  "Cybersecurity",
  "Data Science & Analytics",
  "E-commerce",
  "Education & Training",
  "Energy & Utilities",
  "Environmental Services",
  "Events & Entertainment",
  "Fashion & Apparel",
  "Food & Beverage",
  "Gaming",
  "Government & Public Sector",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Human Resources",
  "Import & Export",
  "Insurance",
  "Interior Design",
  "Internet & Technology",
  "Investment & Venture Capital",
  "IT Services & Consulting",
  "Journalism & Publishing",
  "Law & Legal Services",
  "Logistics & Supply Chain",
  "Luxury Goods",
  "Manufacturing",
  "Marine & Shipping",
  "Mining & Metals",
  "Non-Profit & NGO",
  "Oil & Gas",
  "Pharmaceuticals",
  "Photography & Film",
  "Product Management",
  "Public Relations",
  "Real Estate",
  "Recruitment & Staffing",
  "Research & Development",
  "Retail",
  "Sales",
  "Security Services",
  "Social Media",
  "Software Development",
  "Sports & Fitness",
  "Telecommunications",
  "Textile",
  "Transportation",
  "Travel & Airlines",
  "Veterinary",
  "Warehousing",
  "Waste Management",
  "Other",
];

export const JOB_TITLE_SUGGESTIONS = [
  // Software Development
  "Software Engineer",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Web Developer",
  "Application Developer",
  "Software Architect",
  "Technical Lead",
  "Tech Lead",
  "Engineering Manager",
  "CTO",

  // Internships & Freshers
  "Software Engineer Intern",
  "Software Developer Intern",
  "Frontend Developer Intern",
  "Backend Developer Intern",
  "Full Stack Developer Intern",
  "Web Developer Intern",
  "SDE Intern",
  "Summer Intern",
  "Graduate Trainee",
  "Management Trainee",
  "Engineer Trainee",
  "Software Trainee",
  "Fresher",
  "Associate Software Engineer",
  "Junior Software Engineer",
  "Junior Developer",
  "Trainee Developer",

  // Frontend
  "React Developer",
  "Next.js Developer",
  "Angular Developer",
  "Vue.js Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "UI Developer",

  // Backend
  "Node.js Developer",
  "Express.js Developer",
  "Java Developer",
  "Spring Boot Developer",
  "Python Developer",
  "Django Developer",
  "Flask Developer",
  "PHP Developer",
  "Laravel Developer",
  ".NET Developer",
  "C# Developer",
  "Ruby on Rails Developer",

  // Full Stack Variants
  "MERN Stack Developer",
  "MEAN Stack Developer",
  "Java Full Stack Developer",
  "Python Full Stack Developer",
  ".NET Full Stack Developer",
  "PHP Full Stack Developer",

  // Mobile Development
  "Mobile Developer",
  "Mobile App Developer",
  "Android Developer",
  "Android Engineer",
  "iOS Developer",
  "iOS Engineer",
  "Flutter Developer",
  "React Native Developer",

  // Data & AI
  "Data Analyst",
  "Business Data Analyst",
  "Data Engineer",
  "Big Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Deep Learning Engineer",
  "AI Engineer",
  "Generative AI Engineer",
  "Prompt Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "AI Research Engineer",

  // Cloud & DevOps
  "DevOps Engineer",
  "Cloud Engineer",
  "AWS Engineer",
  "Azure Engineer",
  "Google Cloud Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Infrastructure Engineer",

  // Security
  "Cybersecurity Analyst",
  "Security Engineer",
  "Information Security Analyst",
  "SOC Analyst",
  "Penetration Tester",
  "Ethical Hacker",

  // QA & Testing
  "QA Engineer",
  "QA Analyst",
  "Software Tester",
  "Automation Test Engineer",
  "Manual Tester",
  "Performance Test Engineer",
  "Test Engineer",

  // Database
  "Database Administrator",
  "Database Engineer",
  "SQL Developer",
  "MongoDB Developer",

  // Networking & Systems
  "System Administrator",
  "Network Engineer",
  "Network Administrator",
  "IT Support Engineer",
  "Technical Support Engineer",

  // Design
  "UI Designer",
  "UX Designer",
  "UI/UX Designer",
  "Graphic Designer",
  "Visual Designer",
  "Product Designer",
  "Motion Designer",

  // Product & Management
  "Product Manager",
  "Associate Product Manager",
  "Project Manager",
  "Program Manager",
  "Scrum Master",
  "Business Analyst",
  "Technical Product Manager",

  // Marketing
  "Marketing Manager",
  "Digital Marketing Specialist",
  "Performance Marketing Executive",
  "Growth Marketer",
  "SEO Specialist",
  "SEM Specialist",
  "Content Writer",
  "Content Strategist",
  "Copywriter",
  "Social Media Manager",
  "Brand Manager",

  // Sales
  "Sales Executive",
  "Sales Manager",
  "Business Development Executive",
  "Business Development Associate",
  "Business Development Manager",
  "Account Executive",
  "Account Manager",

  // Customer Success
  "Customer Support",
  "Customer Support Executive",
  "Customer Success Associate",
  "Customer Success Manager",

  // HR
  "HR Executive",
  "HR Manager",
  "Talent Acquisition Specialist",
  "Recruiter",
  "Technical Recruiter",

  // Finance
  "Finance Manager",
  "Financial Analyst",
  "Investment Analyst",
  "Accountant",
  "Chartered Accountant",
  "Finance Executive",

  // Operations
  "Operations Executive",
  "Operations Manager",
  "Operations Analyst",
  "Logistics Coordinator",
  "Supply Chain Manager",
  "Procurement Specialist",

  // Emerging Roles
  "Blockchain Developer",
  "Web3 Developer",
  "AR Developer",
  "VR Developer",
  "Game Developer",
  "Unity Developer",
  "Unreal Engine Developer",
  "Embedded Systems Engineer",
  "IoT Engineer",
  "Robotics Engineer",
];

export const DEPARTMENT_SUGGESTIONS = [
  "Engineering",
  "Product",
  "Design",
  "Marketing",
  "Sales",
  "Finance",
  "Human Resources",
  "Operations",
  "Customer Success",
  "Legal",
  "IT",
  "Data & Analytics",
  "Research & Development",
  "Supply Chain",
  "Procurement",
  "Administration",
  "Business Development",
  "Strategy",
];

export const WORK_TYPES = ["On-site", "Remote", "Hybrid"];

export const JOB_TYPES = [
  "Full-time",
  "Part-time",
  "Contract",
  "Freelance",
  "Internship",
  "Temporary",
];

export const EXP_LEVELS = [
  "Fresher / No Experience",
  "Entry Level (0-1 yr)",
  "Junior (1-2 yrs)",
  "Mid Level (2-5 yrs)",
  "Senior Level (5-8 yrs)",
  "Lead (8+ yrs)",
  "Manager",
  "Director",
  "VP",
  "C-Suite",
];

export const URGENCY_OPTIONS = ["Low", "Medium", "High", "Urgent"];

export const PAY_STRUCTURES = ["Salary Range", "Fixed", "Hourly", "Negotiable"];

export const CURRENCIES = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { code: "SAR", symbol: "ر.س", name: "Saudi Riyal" },
  { code: "QAR", symbol: "ر.ق", name: "Qatari Riyal" },
  { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
  { code: "BHD", symbol: "BD", name: "Bahraini Dinar" },
  { code: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { code: "NPR", symbol: "₨", name: "Nepalese Rupee" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { code: "MXN", symbol: "MX$", name: "Mexican Peso" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "ARS", symbol: "$", name: "Argentine Peso" },
  { code: "COP", symbol: "$", name: "Colombian Peso" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "EGP", symbol: "£", name: "Egyptian Pound" },
];

export const ALL_PERKS = [
  "Health Insurance",
  "Dental & Vision",
  "401(k) / Pension",
  "Paid Time Off",
  "Remote Work",
  "Flexible Hours",
  "Stock Options",
  "Annual Bonus",
  "Learning Budget",
  "Gym Membership",
  "Meal Allowance",
  "Relocation Assistance",
  "Parental Leave",
  "Life Insurance",
  "Travel Allowance",
  "Company Car",
  "Phone Allowance",
  "Internet Allowance",
  "Mental Health Support",
  "Childcare Support",
  "Employee Discounts",
  "Team Events",
  "Free Snacks",
  "Visa Sponsorship",
];
